package View;

import Controller.HRSController;
import Helper.InputHelper;
import Helper.MessageHelper;

import java.util.HashMap;

public class ConfirmBookingFrame extends javax.swing.JFrame {
  private MainView view;
  private HRSController controller;
  private SimulateBookingFrame simulateBookingFrame;
  private HashMap<String, String> tempReservationInfo;
  private String hotelName;
  private String guestName;
  private String roomType;
  private int checkInDate;
  private int checkOutDate;
  private String discountCode;

  /**
   * Creates new form ConfirmBookingFrame
   */
  public ConfirmBookingFrame(MainView view, HRSController controller, String hotelName, String guestName, String roomType, int checkInDate, int checkOutDate, String discountCode) {
    this.view = view;
    this.controller = controller;
    this.hotelName = hotelName;
    this.guestName = guestName;
    this.roomType = roomType;
    this.checkInDate = checkInDate;
    this.checkOutDate = checkOutDate;
    this.discountCode = discountCode;
    initComponents();
    fetchData();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    jLabel17 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jButton2.setBackground(new java.awt.Color(255, 204, 255));
    jButton2.setFont(new java.awt.Font("Clarity City", 2, 14)); // NOI18N
    jButton2.setText("Enter Discount Code");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jButton3.setBackground(new java.awt.Color(255, 102, 102));
    jButton3.setFont(new java.awt.Font("Clarity City", 1, 14)); // NOI18N
    jButton3.setForeground(new java.awt.Color(255, 255, 255));
    jButton3.setText("Cancel");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    jButton4.setBackground(new java.awt.Color(153, 255, 153));
    jButton4.setFont(new java.awt.Font("Clarity City", 1, 14)); // NOI18N
    jButton4.setForeground(new java.awt.Color(102, 102, 102));
    jButton4.setText("Confirm Booking");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Clarity City", 1, 14)); // NOI18N
    jLabel2.setText("Guest Name:");

    jLabel3.setFont(new java.awt.Font("Clarity City", 2, 14)); // NOI18N
    jLabel3.setText("guest");

    jLabel4.setFont(new java.awt.Font("Clarity City", 1, 14)); // NOI18N
    jLabel4.setText("Room Type:");

    jLabel5.setFont(new java.awt.Font("Clarity City", 2, 14)); // NOI18N
    jLabel5.setText("Executive");

    jLabel6.setFont(new java.awt.Font("Clarity City", 1, 14)); // NOI18N
    jLabel6.setText("Hotel Name:");

    jLabel7.setFont(new java.awt.Font("Clarity City", 2, 14)); // NOI18N
    jLabel7.setText("hotel");

    jLabel8.setFont(new java.awt.Font("Clarity City", 2, 14)); // NOI18N
    jLabel8.setText("guest");

    jLabel9.setFont(new java.awt.Font("Clarity City", 1, 14)); // NOI18N
    jLabel9.setText("Check-in Date:");

    jLabel10.setFont(new java.awt.Font("Clarity City", 1, 14)); // NOI18N
    jLabel10.setText("Check-out Date:");

    jLabel11.setFont(new java.awt.Font("Clarity City", 2, 14)); // NOI18N
    jLabel11.setText("guest");

    jLabel12.setFont(new java.awt.Font("Clarity City", 1, 36)); // NOI18N
    jLabel12.setText("Confirm Booking");

    jLabel13.setFont(new java.awt.Font("Clarity City", 1, 14)); // NOI18N
    jLabel13.setText("Total Price:");

    jLabel14.setFont(new java.awt.Font("Clarity City", 2, 14)); // NOI18N
    jLabel14.setText("guest");

    jLabel15.setFont(new java.awt.Font("Clarity City", 2, 12)); // NOI18N
    jLabel15.setForeground(new java.awt.Color(102, 102, 102));
    jLabel15.setText("Please check your information details below:");

    jLabel16.setFont(new java.awt.Font("Clarity City", 1, 14)); // NOI18N
    jLabel16.setText("Discount Code:");

    jLabel17.setFont(new java.awt.Font("Clarity City", 2, 14)); // NOI18N
    jLabel17.setText("STAY4_GET1");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel4))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(jLabel14))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jButton2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 260,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 220,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE)));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Cancels booking
   */
  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
    /* Cancel */
    simulateBookingFrame = new SimulateBookingFrame(view, controller, hotelName);
    simulateBookingFrame.setVisible(true);
    ConfirmBookingFrame.this.dispose();
  }// GEN-LAST:event_jButton3ActionPerformed

  /**
   * Confirms booking
   */
  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
    // TODO add your handling code here:
    /* Book */
    boolean isBooked = controller.bookRoom(hotelName, tempReservationInfo.get("Guest Name"),
        tempReservationInfo.get("Room Type"), checkInDate, checkOutDate, tempReservationInfo.get("Discount Code"));
    if (!isBooked) {
      MessageHelper.showErrorMessage("Booking failed.");
      return;
    }
    view.setVisible(true);
    view.refreshHotelList();
    ConfirmBookingFrame.this.dispose();
  }// GEN-LAST:event_jButton4ActionPerformed

  /**
   * Enters discount code
   */
  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
    /* Enter Discount Code */
    String discountCodeInput = InputHelper.askInputString("Enter Discount Code");
    if (controller.isDiscountApplied(tempReservationInfo, discountCodeInput)) {
      // refresh current view
      ConfirmBookingFrame newConfirmBookingFrame = new ConfirmBookingFrame(view, controller, hotelName, guestName, roomType, checkInDate, checkOutDate, discountCodeInput);
      newConfirmBookingFrame.setVisible(true);
      ConfirmBookingFrame.this.dispose();
    }
  }// GEN-LAST:event_jButton2ActionPerformed

  /**
   * Fetches data from the controller
   */
  public void fetchData() {
    tempReservationInfo = controller.createTemporaryReservation(hotelName, roomType, guestName, checkInDate,
        checkOutDate, discountCode);
    if (tempReservationInfo != null) {
      jLabel7.setText(hotelName); // hotel name
      jLabel3.setText(tempReservationInfo.get("Guest Name")); // guest name
      jLabel5.setText(tempReservationInfo.get("Room Type")); // room type
      jLabel8.setText(tempReservationInfo.get("Check In Date")); // check in date
      jLabel11.setText(tempReservationInfo.get("Check Out Date")); // check out date
      jLabel14.setText(tempReservationInfo.get("Total Price")); // total price
      jLabel17.setText(tempReservationInfo.get("Discount Code")); // discount code
    } else {
      // if
      MessageHelper.showErrorMessage("Invalid data marker. Returning...");
      simulateBookingFrame = new SimulateBookingFrame(view, controller, hotelName);
      simulateBookingFrame.setVisible(true);
      ConfirmBookingFrame.this.dispose();
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  // End of variables declaration//GEN-END:variables
}
